// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmYZQx7tgPss8bzV00SX5LEgsfQCkRzoA',
    appId: '1:990118197281:web:bb9f2fc1e23b7a467c4b60',
    messagingSenderId: '990118197281',
    projectId: 'stud-teach',
    authDomain: 'stud-teach.firebaseapp.com',
    storageBucket: 'stud-teach.appspot.com',
    measurementId: 'G-FGP555T4NE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEtXrJTnMCwuDolMgK78gtHEOR1ahP5rk',
    appId: '1:990118197281:android:272691f46e5d30e17c4b60',
    messagingSenderId: '990118197281',
    projectId: 'stud-teach',
    storageBucket: 'stud-teach.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAd9WF9l8Ctqu5hwSJt89t4BzVPLZnXGH0',
    appId: '1:990118197281:ios:b38e13d86835fd2a7c4b60',
    messagingSenderId: '990118197281',
    projectId: 'stud-teach',
    storageBucket: 'stud-teach.appspot.com',
    iosBundleId: 'com.example.studtech',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAd9WF9l8Ctqu5hwSJt89t4BzVPLZnXGH0',
    appId: '1:990118197281:ios:b38e13d86835fd2a7c4b60',
    messagingSenderId: '990118197281',
    projectId: 'stud-teach',
    storageBucket: 'stud-teach.appspot.com',
    iosBundleId: 'com.example.studtech',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAmYZQx7tgPss8bzV00SX5LEgsfQCkRzoA',
    appId: '1:990118197281:web:ebef4eb422061e297c4b60',
    messagingSenderId: '990118197281',
    projectId: 'stud-teach',
    authDomain: 'stud-teach.firebaseapp.com',
    storageBucket: 'stud-teach.appspot.com',
    measurementId: 'G-ST378H7H53',
  );
}
